      - name: Debug secrets (do not log actual values)
        run: |
          echo "MAIL_SERVER is set: ${{ secrets.MAIL_SERVER != '' }}"
          echo "MAIL_PORT is set: ${{ secrets.MAIL_PORT != '' }}"
          echo "MAIL_USERNAME is set: ${{ secrets.MAIL_USERNAME != '' }}"
          echo "MAIL_PASSWORD is set: ${{ secrets.MAIL_PASSWORD != '' }}"

      - name: Send Test Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          secure: true # set explicitly if using port 465 (SSL)
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "✅ GitHub Actions Email Test"
          body: |
            This is a test email sent by GitHub Actions.

            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Run ID: ${{ github.run_id }}

            Check the logs here:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.MAIL_USERNAME }}
          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>
